/*
  /rss.xml -- the Traditional Chinese (default locale) news feed.
  One feed per locale, generated by lib/rss.ts; this file only binds the
  language, the same way pages/news/index.astro does.
*/
import type { APIRoute } from "astro";
import { newsFeedResponse } from "@/lib/rss";

export const prerender = true;

export const GET: APIRoute = ({ site }) => newsFeedResponse("zh-Hant", site);
